Store Front/CorePackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Cart Item-{0000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Item__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Item__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Item_Type</valueSetName>
    </valueSet>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1000</defaultValue>
    <label>Quantity</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <displayFormat>Purchase-{0000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Purchase__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Purchase__c/fields/Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card__c</fullName>
    <label>Credit Card</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Purchase__c/fields/Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Code__c</fullName>
    <label>Zip Code</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Store Front/CorePackage/main/default/globalValueSets/Item_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Baked</fullName>
    </customValue>
    <customValue>
        <fullName>Beverage</fullName>
    </customValue>
    <customValue>
        <fullName>Dairy</fullName>
    </customValue>
    <customValue>
        <fullName>Frozen</fullName>
    </customValue>
    <masterLabel>Item Type</masterLabel>
</GlobalValueSet>

Store Front/CorePackage/main/default/classes/ProductDisplayControllerTest.cls
@isTest
public class ProductDisplayControllerTest {
    @testSetup
    static void Setup(){
        List<String> itemNames = new List<String>{'Bagels','Bread','Sprite','Coke'};
            List<Item__c> itemList = new List<Item__c>();
        for(String itemName : itemNames){
            itemList.add(new Item__c(Name=itemName, Item_Type__c='Dairy',IsActive__c=true,Price__c=3.99, Quantity__c=10)); 
        }
        insert itemList;
    }
    @isTest 
    static void Main(){
        User me = [SELECT Name, FirstName From User Where FirstName='User'];
        
        System.runAs(me){
            List<Item__c> All = ProductDisplayController.search('All','Ba');
            List<Item__c> Dairy = ProductDisplayController.search('Dairy','Ba');
            List<Item__c> All2 = ProductDisplayController.search('All','null');
            List<Item__c> Dairy2 = ProductDisplayController.search('Dairy','null');
            
            System.assertEquals(4, Dairy2.size());
            System.assertEquals(1, Dairy.size());
            System.assertEquals(4, All2.size());
            System.assertEquals(1, All.size());
            
            Item__c item = [SELECT Id FROM Item__c LIMIT 1];
            Item__c item2 = ProductDisplayController.returnItem(item.Id);
            
            for(Integer i = 0;i<5;i++){
                ProductDisplayController.addItemToCart(item2.Id);
            }
            
            List<Cart_Item__c> CI = ProductDisplayController.returnCart();
            
            System.assertEquals(5,CI.size());
            
            ProductDisplayController.removeSingleItem(item2.id);
            
            CI = ProductDisplayController.returnCart();
            
            System.assertEquals(4,CI.size());
            
            ProductDisplayController.removeItemsFromCart(item2.id);
            
            CI = ProductDisplayController.returnCart();
            
            System.assertEquals(0,CI.size());
            
            for(Integer i = 0;i<5;i++){
                ProductDisplayController.addItemToCart(item2.Id);
            }
            
            Purchase__c testProduct = new Purchase__c(Address__c='221B Baker Street',	Credit_Card__c='1111111111111111',Zip_Code__c='12345',City__c='Westerpoint');
            
            insert testProduct;
            Test.startTest();
            
            ProductDisplayController.cartCheck();
            
            for(Integer i = 0;i<11;i++){
                ProductDisplayController.addItemToCart(item2.Id);
            }
            
            Cart__c cart = ProductDisplayController.returnCartTop();
            
            testProduct = new Purchase__c(Address__c='221B Baker Street',	Credit_Card__c='1111111111111111',Zip_Code__c='12345',City__c='Westerpoint');
            
            
            try{
                insert testProduct;
            }catch(Exception e){
                System.debug(e);
            }
            
            Test.stopTest();            
            List<ProductDisplayController.PurchaseWrapper> purWrap = ProductDisplayController.PreviousPurchases();
            
        }
    }
}