Store Front/CorePackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Cart Item-{0000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Item__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/classes/CartTriggerHelper.cls
public class CartTriggerHelper {
    public static void updateSubtotal(List<Cart_Item__c> cart){
        Cart__c crt = [SELECT Id FROM Cart__c WHERE ID = :cart[0].Cart__c];
        crt.Subtotal__c = 0.0;
        for(Cart_Item__c CI : [SELECT Item__r.Price__c, Cart__r.Id From Cart_Item__c WHERE Cart__r.Id = :crt.id]){
            if(CI.Item__r.Price__c!=null)
            	crt.Subtotal__c += CI.Item__r.Price__c;
        }
        crt.Total__c = crt.Subtotal__c*1.0825;
        update crt;
    }
}