Store Front/CorePackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <label>UserID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Cart Item-{0000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Item__c/fields/DisplayURL__c.field-meta.xml
<CustomField>
    <fullName>DisplayURL__c</fullName>
    <label>DisplayURL</label>
    <type>Url</type>
</CustomField>

Store Front/CorePackage/main/default/classes/ProductDisplayController.cls
public class ProductDisplayController {
	@AuraEnabled
    public static List<Item__c> search(String filter){
        List<Item__c> pro =[SELECT Id, Name, DisplayURL__c, IsActive__c FROM Item__c WHERE IsActive__c=true];
        System.debug(pro.size());
        return pro;
    }
    @AuraEnabled
    public static void addItemToCart(Id item){
		Item__c itemName = [SELECT Id, Name FROM Item__c WHERE id=:item];
        Cart__c cart = [SELECT Id, UserID__c FROM Cart__c WHERE UserID__c = :UserInfo.getUserId()];
        if(cart!=null){
			Cart_Item__c CI = new Cart_Item__c(Item__c = itemName.id, Cart__c=cart.id);
        	insert CI;
        }
    }
    @AuraEnabled
    public static List<Cart_Item__c> returnCart(){
        Id userID = UserInfo.getUserId();
        return [SELECT Item__r.Name, Cart__r.UserID__c FROM Cart_Item__c WHERE Cart__r.UserID__c = :userID];
    }
}