Store Front/CorePackage/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <label>Cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <label>UserID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>Cart Item-{0000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Cart_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Item__r.Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1000</defaultValue>
    <label>Quantity</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Store Front/CorePackage/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <displayFormat>Purchase-{0000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Store Front/CorePackage/main/default/classes/PurchaseTriggerHelper.cls
/*
* Name: PurchaseTriggerHelper
* Author: Kameron Fincher
* Description: Meant to perform validation checks on purchases and transfer carts properly
*/
public class PurchaseTriggerHelper {
    /*public static void UpdateDate(List<Purchase__c> pur){
for(Purchase__c IndPur : pur){
IndPur.
}
}*/
    public static void TransferToPurchase(List<Purchase__c> pur){
        Cart__c cart = [SELECT Id, IsActive__c, UserID__c from Cart__c WHERE UserID__c = :UserInfo.getUserId() AND IsActive__c = true];    
        cart.Purchase__c = pur[0].id;
        cart.IsActive__c = false;
       
        update cart;
        
        ProductDisplayController.PurchaseWrapper PW = ProductDisplayController.PreviousPurchase(); 
        User thisUser = [SELECT Email FROM User WHERE ID = :UserInfo.getUserId()];
        sendEmailConfirmation(thisUser.email, PW);
        
    }
    
    public class ItemWrapper{
        Integer Amount;
        Integer Quantity;
        String Name;
        
        public ItemWrapper(Integer Amount, Decimal Quantity, String Name){
            this.Amount = Amount;
            this.Quantity = Integer.valueOf(Quantity);
            this.Name = Name;
        }
        
    }
    
    public static void AdvancedValidity(List<Purchase__c> pur){        
        Map<Id, ItemWrapper> CIMap = new Map<Id, ItemWrapper>(); 
        
        for(Cart_Item__c IndCI : [SELECT Item__r.Name, Item__r.Quantity__c, Cart__r.IsActive__c FROM Cart_Item__c WHERE Cart__r.IsActive__c = true]){
            Id temp = IndCI.Item__r.Id;
            ItemWrapper IW = CIMap.get(temp);
            
            if(IW!=null){
                IW.Amount+=1;
                CIMap.put(temp, IW);
            }else{
                CIMap.put(temp, new ItemWrapper(1, IndCI.Item__r.Quantity__c, IndCI.Item__r.Name));
            }
            
        }
        
        
        
        for(Id key : CIMap.keyset()){
            if(CIMap.get(key).Amount>CIMap.get(key).Quantity){
                System.debug(key + ' out of stock');
                sendEmail(CIMap.get(key).Name);
                pur[0].addError(CIMap.get(key).Name + ' out of stock');
            }  
        }
        
        List<Item__c> itemsToUpdate = [SELECT Name, Id, Quantity__c FROM Item__c Where ID in :CIMap.keyset()]; 
        for(item__c item : itemsToUpdate){
            item.Quantity__c -= CIMap.get(item.Id).Amount;
        }
        
        update itemsToUpdate;
    }
    public static void sendEmailConfirmation(String email, ProductDisplayController.PurchaseWrapper items){   
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //String toRecipients = 'storefrontsf@gmail.com';
        String[] toAddresses = new String[]{email };
            mail.setToAddresses(toAddresses);
        mail.setReplyTo('kameron.fincher@revature.net');
        mail.setSenderDisplayName('Kameron Fincher');
        mail.setSubject('Receipt for transaction');
        String bodyText = 'Your order is on the way!<br>'+purchaseParser(items);
        mail.setHtmlBody(bodyText);
        Messaging.SendEmailResult [] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
    }
    public static String purchaseParser(ProductDisplayController.PurchaseWrapper items){
        String resultString = '';
        for(ProductDisplayController.CartItemWrapper CIW : items.Items){
            resultString+= '$'+(CIW.Amount*CIW.Item.Price__c)+' '+CIW.Item.Item__r.Name+' x'+CIW.Amount+'<br>';
        }
        resultString += +'Subtotal: $'+items.Cart.Subtotal__c+'<br>';
        resultString += +'Total: $'+items.Cart.Total__c+'<br>';
        return resultString;
    }
    public static void sendEmail(String name){   
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String toRecipients = 'storefrontsf@gmail.com';
        String[] toAddresses = new String[]{'storefrontsf@gmail.com' };
            mail.setToAddresses(toAddresses);
        mail.setReplyTo('kameron.fincher@revature.net');
        mail.setSenderDisplayName('Kameron Fincher');
        mail.setSubject('Item out of stock!');
        String bodyText = name+ ' is currently our of stock! Please place an order no this ASAP.';
        mail.setHtmlBody(bodyText);
        Messaging.SendEmailResult [] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {mail});
    }
}